#!/usr/bin/env python
# coding: utf-8
# @Time    : 2020/12/1 23:46
# @Author  : Li XiaoJun
# @Site    : 
# @File    : channel.py

arkit_channels = {
    "browDown_L": {},
    "browDown_R": {},
    "browInnerUp": {},
    "browOuterUp_L": {},
    "browOuterUp_R": {},
    "cheekPuff": {},
    "cheekSquint_L": {},
    "cheekSquint_R": {},
    "eyeBlink_L": {},
    "eyeBlink_R": {},
    "eyeLookDown_L": {},
    "eyeLookDown_R": {},
    "eyeLookIn_L": {},
    "eyeLookIn_R": {},
    "eyeLookOut_L": {},
    "eyeLookOut_R": {},
    "eyeLookUp_L": {},
    "eyeLookUp_R": {},
    "eyeSquint_L": {},
    "eyeSquint_R": {},
    "eyeWide_L": {},
    "eyeWide_R": {},
    "jawForward": {},
    "jawLeft": {},
    "jawOpen": {},
    "jawRight": {},
    "mouthClose": {},
    "mouthDimple_L": {},
    "mouthDimple_R": {},
    "mouthFrown_L": {},
    "mouthFrown_R": {},
    "mouthFunnel": {},
    "mouthLeft": {},
    "mouthLowerDown_L": {},
    "mouthLowerDown_R": {},
    "mouthPress_L": {},
    "mouthPress_R": {},
    "mouthPucker": {},
    "mouthRight": {},
    "mouthRollLower": {},
    "mouthRollUpper": {},
    "mouthShrugLower": {},
    "mouthShrugUpper": {},
    "mouthSmile_L": {},
    "mouthSmile_R": {},
    "mouthStretch_L": {},
    "mouthStretch_R": {},
    "mouthUpperUp_L": {},
    "mouthUpperUp_R": {},
    "noseSneer_L": {},
    "noseSneer_R": {},
}

face_unity_channels = {
    "expression1": {},
    "expression2": {},
    "expression3": {},
    "expression4": {},
    "expression5": {},
    "expression6": {},
    "expression7": {},
    "expression8": {},
    "expression9": {},
    "expression10": {},
    "expression11": {},
    "expression12": {},
    "expression13": {},
    "expression14": {},
    "expression15": {},
    "expression16": {},
    "expression17": {},
    "expression18": {},
    "expression19": {},
    "expression20": {},
    "expression21": {},
    "expression22": {},
    "expression23": {},
    "expression24": {},
    "expression25": {},
    "expression26": {},
    "expression27": {},
    "expression28": {},
    "expression29": {},
    "expression30": {},
    "expression31": {},
    "expression32": {},
    "expression33": {},
    "expression34": {},
    "expression35": {},
    "expression36": {},
    "expression37": {},
    "expression38": {},
    "expression39": {},
    "expression40": {},
    "expression41": {},
    "expression42": {},
    "expression43": {},
    "expression44": {},
    "expression45": {},
}
