# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/work/XDLibs/ui/rs.ui'
#
# Created: Thu Aug 20 20:37:03 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_rig = QtWidgets.QWidget()
        self.tab_rig.setObjectName("tab_rig")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_rig)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.tab_rig)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_10.addWidget(self.pushButton_11)
        self.line = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_10.addWidget(self.pushButton_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.tab_rig)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 0, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.frame_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(self.tab_rig)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_2.setProperty("value", 1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_rig, "")
        self.tab_modules = QtWidgets.QWidget()
        self.tab_modules.setObjectName("tab_modules")
        self.tabWidget.addTab(self.tab_modules, "")
        self.tab_add_controls = QtWidgets.QWidget()
        self.tab_add_controls.setObjectName("tab_add_controls")
        self.tabWidget.addTab(self.tab_add_controls, "")
        self.tab_twists = QtWidgets.QWidget()
        self.tab_twists.setObjectName("tab_twists")
        self.tabWidget.addTab(self.tab_twists, "")
        self.tab_inbetweens = QtWidgets.QWidget()
        self.tab_inbetweens.setObjectName("tab_inbetweens")
        self.tabWidget.addTab(self.tab_inbetweens, "")
        self.tab_object_spaces = QtWidgets.QWidget()
        self.tab_object_spaces.setObjectName("tab_object_spaces")
        self.tabWidget.addTab(self.tab_object_spaces, "")
        self.tab_controllers = QtWidgets.QWidget()
        self.tab_controllers.setObjectName("tab_controllers")
        self.tabWidget.addTab(self.tab_controllers, "")
        self.tab_tools = QtWidgets.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        self.tabWidget.addTab(self.tab_tools, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 30))
        self.menubar.setObjectName("menubar")
        self.menuRig = QtWidgets.QMenu(self.menubar)
        self.menuRig.setObjectName("menuRig")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSave_Pose = QtWidgets.QAction(MainWindow)
        self.actionSave_Pose.setObjectName("actionSave_Pose")
        self.actionReset_Pose = QtWidgets.QAction(MainWindow)
        self.actionReset_Pose.setObjectName("actionReset_Pose")
        self.actionPosers = QtWidgets.QAction(MainWindow)
        self.actionPosers.setObjectName("actionPosers")
        self.actionControls = QtWidgets.QAction(MainWindow)
        self.actionControls.setObjectName("actionControls")
        self.actionJoints = QtWidgets.QAction(MainWindow)
        self.actionJoints.setObjectName("actionJoints")
        self.actionGeometry = QtWidgets.QAction(MainWindow)
        self.actionGeometry.setObjectName("actionGeometry")
        self.actionJoints_Template = QtWidgets.QAction(MainWindow)
        self.actionJoints_Template.setObjectName("actionJoints_Template")
        self.actionGeometry_Template = QtWidgets.QAction(MainWindow)
        self.actionGeometry_Template.setObjectName("actionGeometry_Template")
        self.actionGeometry_Reference = QtWidgets.QAction(MainWindow)
        self.actionGeometry_Reference.setObjectName("actionGeometry_Reference")
        self.actionPosers_Axises = QtWidgets.QAction(MainWindow)
        self.actionPosers_Axises.setObjectName("actionPosers_Axises")
        self.actionSkeleton_LRA = QtWidgets.QAction(MainWindow)
        self.actionSkeleton_LRA.setObjectName("actionSkeleton_LRA")
        self.actionControl_Sets = QtWidgets.QAction(MainWindow)
        self.actionControl_Sets.setObjectName("actionControl_Sets")
        self.actionHuman_IK_Transfer_Tool = QtWidgets.QAction(MainWindow)
        self.actionHuman_IK_Transfer_Tool.setObjectName("actionHuman_IK_Transfer_Tool")
        self.actionMudule_Builder = QtWidgets.QAction(MainWindow)
        self.actionMudule_Builder.setObjectName("actionMudule_Builder")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        self.actionDebug.setObjectName("actionDebug")
        self.actionHome_Page = QtWidgets.QAction(MainWindow)
        self.actionHome_Page.setObjectName("actionHome_Page")
        self.actionTutorials = QtWidgets.QAction(MainWindow)
        self.actionTutorials.setObjectName("actionTutorials")
        self.actionHelp_Mode = QtWidgets.QAction(MainWindow)
        self.actionHelp_Mode.setObjectName("actionHelp_Mode")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuRig.addAction(self.actionNew)
        self.menuRig.addAction(self.actionSave)
        self.menuRig.addAction(self.actionLoad)
        self.menuRig.addAction(self.actionDelete)
        self.menuRig.addSeparator()
        self.menuRig.addAction(self.actionSave_Pose)
        self.menuRig.addAction(self.actionReset_Pose)
        self.menuDisplay.addAction(self.actionPosers)
        self.menuDisplay.addAction(self.actionControls)
        self.menuDisplay.addAction(self.actionJoints)
        self.menuDisplay.addAction(self.actionGeometry)
        self.menuDisplay.addSeparator()
        self.menuDisplay.addAction(self.actionJoints_Template)
        self.menuDisplay.addAction(self.actionGeometry_Template)
        self.menuDisplay.addAction(self.actionGeometry_Reference)
        self.menuDisplay.addSeparator()
        self.menuDisplay.addAction(self.actionPosers_Axises)
        self.menuDisplay.addAction(self.actionSkeleton_LRA)
        self.menuTools.addAction(self.actionControl_Sets)
        self.menuTools.addAction(self.actionHuman_IK_Transfer_Tool)
        self.menuTools.addAction(self.actionMudule_Builder)
        self.menuOptions.addAction(self.actionDebug)
        self.menuHelp.addAction(self.actionHome_Page)
        self.menuHelp.addAction(self.actionTutorials)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp_Mode)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuRig.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_11.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Publish Rig", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "Select Skin Joint", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("MainWindow", "Save Pose", None, -1))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("MainWindow", "Reset Pose", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Posers Size", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Joints Size", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rig), QtWidgets.QApplication.translate("MainWindow", "Rig", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_modules), QtWidgets.QApplication.translate("MainWindow", "Modules", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_add_controls), QtWidgets.QApplication.translate("MainWindow", "Add Controls", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_twists), QtWidgets.QApplication.translate("MainWindow", "Twists", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inbetweens), QtWidgets.QApplication.translate("MainWindow", "Inbetweens", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_object_spaces), QtWidgets.QApplication.translate("MainWindow", "ObjectSpaces", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_controllers), QtWidgets.QApplication.translate("MainWindow", "Controllers", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tools), QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.menuRig.setTitle(QtWidgets.QApplication.translate("MainWindow", "Rig", None, -1))
        self.menuDisplay.setTitle(QtWidgets.QApplication.translate("MainWindow", "Display", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.menuOptions.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.actionDelete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.actionSave_Pose.setText(QtWidgets.QApplication.translate("MainWindow", "Save Pose", None, -1))
        self.actionReset_Pose.setText(QtWidgets.QApplication.translate("MainWindow", "Reset Pose", None, -1))
        self.actionPosers.setText(QtWidgets.QApplication.translate("MainWindow", "Posers", None, -1))
        self.actionControls.setText(QtWidgets.QApplication.translate("MainWindow", "Controls", None, -1))
        self.actionJoints.setText(QtWidgets.QApplication.translate("MainWindow", "Joints", None, -1))
        self.actionGeometry.setText(QtWidgets.QApplication.translate("MainWindow", "Geometry", None, -1))
        self.actionJoints_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Joints Template", None, -1))
        self.actionGeometry_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Geometry Template", None, -1))
        self.actionGeometry_Reference.setText(QtWidgets.QApplication.translate("MainWindow", "Geometry Reference", None, -1))
        self.actionPosers_Axises.setText(QtWidgets.QApplication.translate("MainWindow", "Posers Axises", None, -1))
        self.actionSkeleton_LRA.setText(QtWidgets.QApplication.translate("MainWindow", "Skeleton LRA", None, -1))
        self.actionControl_Sets.setText(QtWidgets.QApplication.translate("MainWindow", "Control Sets", None, -1))
        self.actionHuman_IK_Transfer_Tool.setText(QtWidgets.QApplication.translate("MainWindow", "Human IK Transfer Tool...", None, -1))
        self.actionMudule_Builder.setText(QtWidgets.QApplication.translate("MainWindow", "Mudule Builder...", None, -1))
        self.actionDebug.setText(QtWidgets.QApplication.translate("MainWindow", "Debug", None, -1))
        self.actionHome_Page.setText(QtWidgets.QApplication.translate("MainWindow", "Home Page", None, -1))
        self.actionTutorials.setText(QtWidgets.QApplication.translate("MainWindow", "Tutorials", None, -1))
        self.actionHelp_Mode.setText(QtWidgets.QApplication.translate("MainWindow", "Help Mode", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

